Sprint 4
JuliDeveloper/MovieQuiz pull request #2
Opened 2022-09-17 15:23 UTC by JuliDeveloper

Настроила внешний вид и логику приложения

2022-09-17 16:05 UTC, ABashkirova requested changes
Хорошая и аккуратная работа. Нужно исправить несколько пунктов по чеклисту.

2022-09-17 16:05 UTC, ABashkirova commented on MovieQuiz/AppDelegate.swift
> +        sleep(3)
Эту строчку можно удалить после сдачи работы 👍

2022-09-17 16:05 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet private var textLabel: UILabel!
Возможно в учебнике именно такие имена оставлены, однако заметьте что они не сильно отражают суть содержимого – постер и текст вопроса. Предлагаю переименовать

2022-09-17 16:05 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    }
Мне нравится, что вы выделили код из yesButtonClicked/noButtonClicked  в отдельную функцию. 
Тут можно продолжить улучшения:
1) строки 104-105, 107-108 очень похожи, и их бы как раз вынести в одну функцию. А на вход подавать корректный ли вопрос. 
2) сравнивать текст кнопки с конкретной строчкой в перспективе не лучшая идея, гораздо лучше полагаться на привязанную функцию yesButtonClicked/noButtonClicked. Представьте, что у вас приложение локализованное и на английский язык тоже. Подход не универсален, получается.

2022-09-17 16:05 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
В ближайших спринтах вам расскажут про замыкания и про слабый список захвата, сейчас же предлагаю добавить `[weak self]`. Тогда придется обращаться к методам через `self?`. Также предложу вынести содержимое в отдельную функцию

```suggestion
        let action = UIAlertAction(title: "Сыграть ещё раз", style: .default) { [weak self] _ in
            self?.restartQuiz()
        }
```

2022-09-17 16:05 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
Заметьте, что здесь вы вызываете отложенный (асинхронный) код. Который исполнится через 1 секунду.
За одну секунду пользователь может еще пару раз жмякнуть по кнопке ответа, и вы вызовете еще несколько таких отложенных функций, не контролируя счетчики верных ответов и индекс текущего вопроса.

Предлагаю запретить пользователю нажимать кнопки на время смены вопроса.
<img width="549" alt="Screenshot 2022-09-17 at 18 50 53" src="https://user-images.githubusercontent.com/20269264/190865407-54a967dd-28b3-480a-8280-43152b75f542.png">

2022-09-17 19:05 UTC, JuliDeveloper commented on MovieQuiz/AppDelegate.swift
> +        sleep(3)
Исправлено

2022-09-18 06:36 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    }
Проблема все еще решена лишь на половину: вторая кнопка остается доступной для нажатия.

2022-09-18 06:42 UTC, ABashkirova commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
> +                            <constraint firstItem="6Tk-OE-BBY" firstAttribute="bottom" secondItem="ZGM-jj-t9E" secondAttribute="bottom" constant="20" id="hHk-d3-nAk"/>
Посмотрите на макет еще раз: кнопки прижаты к линии, выделенная область, высотой в 34 пункта, содержит хом-индикатор. Это как раз та самая safe-area. Поэтому здесь расстояние должно быть до нее 0, а не 20.

<img width="549" alt="Screenshot 2022-09-18 at 09 38 46" src="https://user-images.githubusercontent.com/20269264/190889284-b13f46f1-7926-4f00-87ea-baf743fd46f0.png">

2022-09-18 13:06 UTC, JuliDeveloper commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    }
Исправила

2022-09-18 13:06 UTC, JuliDeveloper commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
> +                            <constraint firstItem="6Tk-OE-BBY" firstAttribute="bottom" secondItem="ZGM-jj-t9E" secondAttribute="bottom" constant="20" id="hHk-d3-nAk"/>
Исправила

2022-09-18 17:26 UTC, ABashkirova approved these changes
Отлично, принято! 

Вы здорово и быстро справились с этой задачей, возможно вам будет интересно решить ее более усложненный вариант. Здесь можно доработать ограничения для Auto Layout: адаптировать верстку под iPhone 8, так чтобы вопрос и счетчики помещались на экране. Для этого вам понадобится попробовать более мягкие условия в констрейнтах, которые задают вертикальные размеры. 
Это сложная задача и очень похожа на то, что делают iOS разработчики в ежедневных задачах, при этом зачастую макетов может не хватить и придется подходить еще и творчески к этой задаче :) 

<img width="561" alt="Screenshot 2022-09-18 at 20 12 03" src="https://user-images.githubusercontent.com/20269264/190919967-b7ac1899-b554-454e-a7f9-e5b639bbdf8e.png">

Также, в этой задаче может понадобится понимание про [Content Hugging и Content Compression Priorities](https://krakendev.io/blog/autolayout-magic-like-harry-potter-but-real). 

Это дополнительное задание не обязательно, но будет круто, если вам удасться это сделать 👍

2022-09-18 19:20 UTC, JuliDeveloper commented
@ABashkirova я все поправила для iPhone 8, буду благодарна, если посмотрите :)

2022-09-18 19:48 UTC, ABashkirova commented
Пока вот так: вопрос не уместился.

![Simulator Screen Shot - iPhone 8 - 2022-09-18 at 22 44 48](https://user-images.githubusercontent.com/20269264/190925589-d6f47bea-05d4-4373-ad19-be8c45d14d34.png)

2022-09-18 19:48 UTC, ABashkirova commented
Еще задачки: ориентация только портретная + белый status bar

2022-09-19 13:21 UTC, JuliDeveloper commented
@ABashkirova, может быть есть возможность посмотреть изменения для iPhone 8 еще раз?
Спасибо большое за все комментарии и дополнительные задания:))))

2022-09-19 14:32 UTC, ABashkirova commented
@JuliDeveloper  давайте последний разок, важно научиться самостоятельно проверять свою работу. 
Итак:
1) ориентация и статус бар ✅
2) проблема в 8-ке решена за счет уменьшения кнопок.
-  Обычно если есть возможность обсудить и показать результат дизайнеру – то обычно так и делаю, если его устроит, то этого достаточно. 
- Однако здесь еще можно было пойти за счет сжатия другого элемента – постера. Он достаточно крупный, если его чуть подожмет по высоте, ничего страшного. Здесь можно было использовать констрейнт на ratio с отношением >= (вы использовали это) и приоритетами на вертикальное сжатие у текстовых элементов (чем больше число, тем сильнее сопротивление). 

Оба решения на вкус и цвет, но на мой взгляд кнопки важнее (как элемент дизайн-системы)

2022-09-27 13:26 UTC, merged